from __future__ import annotations

from typing import TYPE_CHECKING, Protocol

if TYPE_CHECKING:
    from src.core.models import Event


class MarketDiscovery(Protocol):
    async def full_scan(self) -> None: ...
    async def poll_loop(self, interval_secs: int) -> None: ...
    async def cleanup_loop(self) -> None: ...
    def register_events(self, events: list[Event]) -> list[str]: ...
    def cleanup_expired(self) -> set[str]: ...
