from typing import Protocol


class ExchangeAPI(Protocol):
    async def batch_create_orders(self, orders: list[dict]) -> dict: ...
    async def cancel_order(self, order_id: str) -> dict: ...
    async def batch_cancel_orders(self, order_ids: list[str]) -> dict: ...
    async def get_positions(self) -> dict: ...
    async def get_open_orders(self) -> dict: ...
    async def get_balance(self) -> dict: ...
    async def get_market_trades(self, ticker: str, limit: int = 10) -> dict: ...
    async def close(self) -> None: ...
