from typing import Protocol


class FeeModel(Protocol):
    def taker_fee(self, price: float) -> float: ...
    def maker_fee(self, price: float) -> float: ...
    def profit_fee(self, gross_profit: float) -> float: ...
