from typing import Protocol


class OrderbookFeed(Protocol):
    async def connect(self) -> None: ...
    async def subscribe(self, market_tickers: list[str]) -> None: ...
    async def subscribe_fills(self) -> None: ...
    async def listen(self) -> None: ...
    async def close(self) -> None: ...
    def stop(self) -> None: ...
