from typing import Protocol


class OrderBuilder(Protocol):
    def build_sell_order(self, ticker: str, price: float, quantity: int, **kwargs) -> dict: ...
    def build_buy_order(self, ticker: str, price: float, quantity: int, **kwargs) -> dict: ...
    def build_close_order(self, ticker: str, quantity: int, **kwargs) -> dict: ...
    def unwrap_order(self, raw: dict) -> dict: ...
